//-------------------------------------------------------------------------------------------------------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs">(c) 2017 Mike Fourie and Contributors (http://www.MSBuildExtensionPack.com) under MIT License. See https://opensource.org/licenses/MIT </copyright>
//-------------------------------------------------------------------------------------------------------------------------------------------------------------------
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.Dlr.DlrTask.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.Dlr.DlrTask.#SetPropertyValue(Microsoft.Build.Framework.TaskPropertyInfo,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.Dlr.DlrTask.#GetPropertyValue(Microsoft.Build.Framework.TaskPropertyInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.Dlr.DlrTaskFactory.#CreateTask(Microsoft.Build.Framework.IBuildEngine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "taskFactoryLoggingHost", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.Dlr.DlrTask.#.ctor(MSBuild.ExtensionPack.TaskFactory.Dlr.DlrTaskFactory,System.Xml.Linq.XElement,Microsoft.Build.Framework.IBuildEngine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "factory", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.Dlr.DlrTask.#.ctor(MSBuild.ExtensionPack.TaskFactory.Dlr.DlrTaskFactory,System.Xml.Linq.XElement,Microsoft.Build.Framework.IBuildEngine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "parameterGroup", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.Dlr.DlrTaskFactory.#Initialize(System.String,System.Collections.Generic.IDictionary`2<System.String,Microsoft.Build.Framework.TaskPropertyInfo>,System.String,Microsoft.Build.Framework.IBuildEngine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.DlrTask.#Execute()")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.DlrTask.#GetPropertyValue(Microsoft.Build.Framework.TaskPropertyInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.DlrTask.#SetPropertyValue(Microsoft.Build.Framework.TaskPropertyInfo,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1500:VariableNamesShouldNotMatchFieldNames", MessageId = "parameterGroup", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.DlrTaskFactory.#Initialize(System.String,System.Collections.Generic.IDictionary`2<System.String,Microsoft.Build.Framework.TaskPropertyInfo>,System.String,Microsoft.Build.Framework.IBuildEngine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "taskFactoryLoggingHost", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.DlrTask.#.ctor(MSBuild.ExtensionPack.TaskFactory.DlrTaskFactory,System.Xml.Linq.XElement,Microsoft.Build.Framework.IBuildEngine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.DlrTaskFactory.#CreateTask(Microsoft.Build.Framework.IBuildEngine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA1801:ReviewUnusedParameters", MessageId = "factory", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.DlrTask.#.ctor(MSBuild.ExtensionPack.TaskFactory.DlrTaskFactory,System.Xml.Linq.XElement,Microsoft.Build.Framework.IBuildEngine)")]
