//-----------------------------------------------------------------------
// <copyright file="GlobalSuppressions.cs">(c) http://www.msbuildextensionpack.com. This source is subject to the Microsoft Permissive License. See http://www.microsoft.com/resources/sharedsource/licensingbasics/sharedsourcelicenses.mspx. All other rights reserved.</copyright>
//-----------------------------------------------------------------------
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA2210:AssembliesShouldHaveValidStrongNames")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.PowerShell.PowerShellTask.#SetPropertyValue(Microsoft.Build.Framework.TaskPropertyInfo,System.Object)", Justification = "TODO: Review")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.PowerShell.PowerShellTask.#GetPropertyValue(Microsoft.Build.Framework.TaskPropertyInfo)", Justification = "TODO: Review")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.PowerShell.PowerShellTaskFactory.#CreateTask(Microsoft.Build.Framework.IBuildEngine)", Justification = "TODO: Review")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.PowerShell.PowerShellTask.#.ctor(System.String)", Justification = "TODO: Review")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.PowerShellTask.#GetPropertyValue(Microsoft.Build.Framework.TaskPropertyInfo)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Design", "CA1062:Validate arguments of public methods", MessageId = "0", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.PowerShellTask.#SetPropertyValue(Microsoft.Build.Framework.TaskPropertyInfo,System.Object)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.PowerShellTaskFactory.#CreateTask(Microsoft.Build.Framework.IBuildEngine)")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Reliability", "CA2000:Dispose objects before losing scope", Scope = "member", Target = "MSBuild.ExtensionPack.TaskFactory.PowerShellTask.#.ctor(System.String)")]
